### PR TITLE
issue 54: support long filenames when creating tar archives

### PR DESCRIPTION
**Pull request by gardenia**
add the TarArchiveOutputStream.LONGFILE_POSIX option creating tar output streams for long filename support.  issue #54

### CODE REVIEW

**Review by Yeening — COMMENTED** [review]
This is really helpful! The only fallback is that the maven-version apache commons-compress package does not contain the tar package. I'll recommend merge after they update their package on maven.

**Comment by thrau** [comment]
sorry i've been a bit unresponsive. i'm wondering whether this flag applies to other archive types as well. i would prefer something less specific to tar files, unless it's only a problem with TAR files. a test case would also be very useful.

**Comment by Yeening** [comment]
> sorry i've been a bit unresponsive. i'm wondering whether this flag applies to other archive types as well. i would prefer something less specific to tar files, unless it's only a problem with TAR files. a test case would also be very useful.
[longFileNameTC.tar.gz](https://github.com/thrau/jarchivelib/files/6470216/longFileNameTC.tar.gz)

Thank you for the reply! I attached a test case, which is a directory with a deep file path inside it. BTW, according to my testing, the long-file-name error is quite like an issue specific to TAR. It doesn't happen with other archive formats during my test.

**Comment by gardenia** [comment]
@thrau I've updated the pull request to include a long filename in the test resources.

the original issue seems limited to tar as the new test resource passed for all the others (and only fails with tar prior to the fix).

**Comment by thrau** [comment]
thanks, i wasn't happy with the formatting and had to fix the permissions inside the archives. i created a new PR and squash merged it into master. thanks for the contribution!

**Pull request closed without merging**
