### PR TITLE
Use PosixFilePermissions to set file permissions instead of using reflection

### PR DESCRIPTION
**Pull request by cliffcotino**
This also makes it possible to run on JDK versions >= 9

### CODE REVIEW

**Comment by r-tock** [comment]
Any plans of merging this in? I see the master issue is closed.

**Comment by thrau** [comment]
sorry i just haven't found the time yet to have a closer look at it. i have concerns about anything that requires Java > 6 in the current major release. seeing as the pressure is building up to upgrade, i may just release 1.0 as is and start 2.x with java 7. i'll free some time this weekend to look into it.

**Comment by cliffcotino** [comment]
if there's a 2.x branch available, I would be glad to base my changes on that

**Comment by thrau** [comment]
@cliffcotino could you rebase your changes to the current master? i reorganized the milestones and will release 1.0.0 once your changes are merged.

**Comment by cliffcotino** [comment]
I just rebased the changes as requested.

**Comment by thrau** [comment]
Those are excellent changes, thank you very much for the contribution!

**Pull request merged**
